### PR TITLE
CLI messages added by run handlers should show contextual help

### LINKED ISSUE #49: cliMessage usage instructions for command print with wrong context?
Here is an example program:

```
require('sywac')
  .command({
    aliases: 'hello <name>',
    desc: 'say hello',
    run: (argv, context) => {
      context.cliMessage('fatal error');
    }
  })
  .help()
  .parseAndExit();
```

If I run `--help` on either the main program or the command, it prints what I would expect:

```
❯ ./example.js --help
Usage: example <command> <args> [options]

Commands:
  hello <name>  say hello                                                           [aliases: hello]

Options:
  --help  Show help                                                       [commands: help] [boolean]

❯ ./example.js hello --help
Usage: example hello <name> [options]

Arguments:
  <name>                                                                         [required] [string]

Options:
  --help  Show help                                                       [commands: help] [boolean]

```

Now, if I generate a built-in error (by forgetting to include the name), the error prints as I expect - I get the second usage instructions above. But if I generate one manually using `context.cliMessage`, like in my example, I get a hybrid, where the arguments are from my command but everything else is from the root program:

```
❯ ./example.js hello world
Usage: example <command> <args> [options]

Commands:
  hello <name>  say hello                                                           [aliases: hello]

Arguments:
  <name>                                                                         [required] [string]

Options:
  --help  Show help                                                       [commands: help] [boolean]

Oops!
```

I would expect my (sub)command's `context` to print usage instructions related to my (sub)command.  Am I using `cliMessage` incorrectly, or is this a bug?

### PR DESCRIPTION
**Pull request by elliot-nelson**
### SUMMARY

Fixes #49 - a CLI message added to context during a command's run handler (instead of setup or parse) ends up displaying help from the wrong level.

### TESTS

Minor adjustment to an existing test to make it more strict.

### CODE REVIEW

File: types/command.js [hunk 1]
```diff
@@ -124,12 +132,13 @@ class TypeCommand extends Type {
...
-      // console.log('command.js postParse > adding deferred help, implicit:', match.implicit)
-      if (!context.output) context.addDeferredHelp(this.api.initHelpBuffer())
+    if (this._initPossibleHelpBuffer(context)) {
       return this.resolve()
     }
-    return this.runHandler(context.argv, context)
+    return Promise.resolve(this.runHandler(context.argv, context)).then(result => {
+      this._initPossibleHelpBuffer(context)
+      return result
+    })
```
Comment (nexdrew) [inline types/command.js:141]: How about we use `await` here instead of `.then()`?

```suggestion
    const result = await this.runHandler(context.argv, context)
    this._initPossibleHelpBuffer(context)
    return result
```

**Comment by elliot-nelson** [comment]
Changes:
  - adjust from then to await
  - a few other style tweaks to match the existing code in the file

Out of curiosity, I notice that a lot of the tests use then chains instead of async/await - is that just a case of a copied pattern?  I'll use await in future (new) tests if so.

**Comment by nexdrew** [comment]
@elliot-nelson As of #53, I refactored the codebase to use async/await everywhere, including tests. Perhaps you just need to rebase your branch from sywac/master?

**Comment by nexdrew** [comment]
Only caveat I see is that a custom default command using `context.cliMessage()` will now output help specific to the default command (instead of the parent context), which looks a little weird if the default command has no non-default aliases:

```js
require('sywac')
  .command({
    aliases: 'hello <name>',
    desc: 'say hello',
    run: (argv, context) => {
      context.cliMessage('fatal error');
    }
  })
  .command({
    flags: '*',
    run: (argv, context) => {
      context.cliMessage('nope')
    }
  })
  .help().style({ hints: s => '' })
  .parseAndExit()
```

```console
$ node pr56.js
Usage: pr56 * [options]

Options:
  --help  Show help

nope
```

But I don't think that's a use-case I care about. If the default command has a non-default alias, then it looks fine.

Considering that this fixes a bug for a use-case I _do_ care about, I'm merging this. It will be included in sywac v2.

Nice work!

**Comment by nexdrew** [comment]
Note that commit 74ade35 has been published to npm as `sywac@2.0.0-rc3`.

There are a couple more things I want to add before the official v2 release is ready, but feel free to use the `rc` in the meantime and let me know if you encounter any problems.
